// Code generated by Kitex v0.5.2. DO NOT EDIT.

package echosvc

import (
	echo "Orbital_Hebao/kitex_servers/kitex_gen/echo"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	EchoMethod(ctx context.Context, req *echo.EchoReq, callOptions ...callopt.Option) (r *echo.EchoResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kEchoSvcClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kEchoSvcClient struct {
	*kClient
}

func (p *kEchoSvcClient) EchoMethod(ctx context.Context, req *echo.EchoReq, callOptions ...callopt.Option) (r *echo.EchoResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.EchoMethod(ctx, req)
}
