// Code generated by hertz generator.

package main

import (
	"github.com/Linda-ui/orbital_HeBao/hertz_gateway/config"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/hertz-contrib/pprof"
)

func main() {
	h := server.Default(server.WithHostPorts(config.ServiceAddr))
	h.Name = config.ServiceName

	pprof.Register(h)
	register(h)

	h.Spin()
}
