// Code generated by Kitex v0.5.2. DO NOT EDIT.

package echosvc

import (
	echo "github.com/Linda-ui/orbital_HeBao/kitex_services/echo/kitex_gen/echo"
	server "github.com/cloudwego/kitex/server"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler echo.EchoSvc, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
